'use strict';

const codes = [
    { name: 'ACCEPTED', code: 202, desc: 'Accepted' },
    { name: 'BAD_GATEWAY', code: 502, desc: 'Bad Gateway' },
    { name: 'BAD_REQUEST', code: 400, desc: 'Bad Request' },
    { name: 'CONFLICT', code: 409, desc: 'Conflict' },
    { name: 'CONTINUE', code: 100, desc: 'Continue' },
    { name: 'CREATED', code: 201, desc: 'Created' },
    { name: 'EXPECTATION_FAILED', code: 417, desc: 'Expectation Failed' },
    { name: 'FAILED_DEPENDENCY', code: 424, desc: 'Failed Dependency' },
    { name: 'FORBIDDEN', code: 403, desc: 'Forbidden' },
    { name: 'GATEWAY_TIMEOUT', code: 504, desc: 'Gateway Timeout' },
    { name: 'GONE', code: 410, desc: 'Gone' },
    { name: 'HTTP_VERSION_NOT_SUPPORTED', code: 505, desc: 'HTTP Version Not Supported' },
    { name: 'INSUFFICIENT_SPACE_ON_RESOURCE', code: 419, desc: 'Insufficient Space on Resource' },
    { name: 'INSUFFICIENT_STORAGE', code: 507, desc: 'Insufficient Storage' },
    { name: 'INTERNAL_SERVER_ERROR', code: 500, desc: 'Server Error' },
    { name: 'LENGTH_REQUIRED', code: 411, desc: 'Length Required' },
    { name: 'LOCKED', code: 423, desc: 'Locked' },
    { name: 'METHOD_FAILURE', code: 420, desc: 'Method Failure' },
    { name: 'METHOD_NOT_ALLOWED', code: 405, desc: 'Method Not Allowed' },
    { name: 'MOVED_PERMANENTLY', code: 301, desc: 'Moved Permanently' },
    { name: 'MOVED_TEMPORARILY', code: 302, desc: 'Moved Temporarily' },
    { name: 'MULTI_STATUS', code: 207, desc: 'Multi-Status' },
    { name: 'MULTIPLE_CHOICES', code: 300, desc: 'Multiple Choices' },
    { name: 'NETWORK_AUTHENTICATION_REQUIRED', code: 511, desc: 'Network Authentication Required' },
    { name: 'NO_CONTENT', code: 204, desc: 'No Content' },
    { name: 'NON_AUTHORITATIVE_INFORMATION', code: 203, desc: 'Non Authoritative Information' },
    { name: 'NOT_ACCEPTABLE', code: 406, desc: 'Not Acceptable' },
    { name: 'NOT_FOUND', code: 404, desc: 'Not Found' },
    { name: 'NOT_IMPLEMENTED', code: 501, desc: 'Not Implemented' },
    { name: 'NOT_MODIFIED', code: 304, desc: 'Not Modified' },
    { name: 'OK', code: 200, desc: 'OK' },
    { name: 'PARTIAL_CONTENT', code: 206, desc: 'Partial Content' },
    { name: 'PAYMENT_REQUIRED', code: 402, desc: 'Payment Required' },
    { name: 'PRECONDITION_FAILED', code: 412, desc: 'Precondition Failed' },
    { name: 'PRECONDITION_REQUIRED', code: 428, desc: 'Precondition Required' },
    { name: 'PROCESSING', code: 102, desc: 'Processing' },
    { name: 'PROXY_AUTHENTICATION_REQUIRED', code: 407, desc: 'Proxy Authentication Required' },
    { name: 'REQUEST_HEADER_FIELDS_TOO_LARGE', code: 431, desc: 'Request Header Fields Too Large' },
    { name: 'REQUEST_TIMEOUT', code: 408, desc: 'Request Timeout' },
    { name: 'REQUEST_TOO_LONG', code: 413, desc: 'Request Entity Too Large' },
    { name: 'REQUEST_URI_TOO_LONG', code: 414, desc: 'Request-URI Too Long' },
    { name: 'REQUESTED_RANGE_NOT_SATISFIABLE', code: 416, desc: 'Requested Range Not Satisfiable' },
    { name: 'RESET_CONTENT', code: 205, desc: 'Reset Content' },
    { name: 'SEE_OTHER', code: 303, desc: 'See Other' },
    { name: 'SERVICE_UNAVAILABLE', code: 503, desc: 'Service Unavailable' },
    { name: 'SWITCHING_PROTOCOLS', code: 101, desc: 'Switching Protocols' },
    { name: 'TEMPORARY_REDIRECT', code: 307, desc: 'Temporary Redirect' },
    { name: 'TOO_MANY_REQUESTS', code: 429, desc: 'Too Many Requests' },
    { name: 'UNAUTHORIZED', code: 401, desc: 'Unauthorized' },
    { name: 'UNPROCESSABLE_ENTITY', code: 422, desc: 'Unprocessable Entity' },
    { name: 'UNSUPPORTED_MEDIA_TYPE', code: 415, desc: 'Unsupported Media Type' },
    { name: 'USE_PROXY', code: 305, desc: 'Use Proxy' }
];

let httpError = module.exports = {};
codes.forEach((status) => {
    httpError[status.name] = status.code;
});